version: '3.1'

services:
  client:
    container_name: client-container
    restart: always
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - api

  api:
    container_name: api-container
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    # depends_on:
    #   - db

    # db:
    #   image: mysql:5.7
    #   restart: always
    #   environment:
    #     MYSQL_ROOT_PASSWORD: example
    #     MYSQL_DATABASE: users
    #     MYSQL_USER: test
    #     MYSQL_PASSWORD: test1234
    #   ports:
    #     - "3307:3306"
    #   volumes:
    #     - ./docker/data/db:/var/lib/mysql
